import type { Course } from './types';


export const MOCK_COURSES: Course[] = [
  // ==================== WEB DEVELOPMENT ====================
  {
    id: 'web-101',
    title: 'HTML5 & CSS3 Essentials',
    description: 'Learn the foundational languages of the web. Build responsive, semantic layouts from scratch using Flexbox, CSS Grid, and media queries.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['HTML', 'CSS', 'Responsive Design'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 12,
    provider: 'CodeAcademy'
  },
  {
    id: 'web-102',
    title: 'Modern JavaScript Basics',
    description: 'Master core JavaScript concepts: variables, functions, scopes, DOM manipulation, arrays, event handling, and modern ES6+ features.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['JavaScript', 'DOM Manipulation', 'ES6+'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 18,
    provider: 'Scrimba'
  },
  {
    id: 'web-103',
    title: 'Git & Version Control',
    description: 'Learn how to track code changes, collaborate with other developers using GitHub, resolve merge conflicts, and manage feature branches.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['Git', 'GitHub', 'Version Control'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 6,
    provider: 'GitHub Learning Lab'
  },
  {
    id: 'web-201',
    title: 'React Fundamentals',
    description: 'Understand component-based architectures. Master React hooks, state management, props, side effects, and routing.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['React', 'State Management', 'SPA Architecture'],
    prerequisite_skills: ['HTML', 'JavaScript'],
    difficulty: 'intermediate',
    estimated_hours: 24,
    provider: 'Frontend Masters'
  },
  {
    id: 'web-202',
    title: 'Node.js & Express.js Backends',
    description: 'Build fast, scalable server-side applications. Cover routing, middleware, RESTful API design, and request/response lifecycles.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['Node.js', 'Express.js', 'Backend Development', 'APIs'],
    prerequisite_skills: ['JavaScript'],
    difficulty: 'intermediate',
    estimated_hours: 20,
    provider: 'Udemy'
  },
  {
    id: 'web-203',
    title: 'SQL & Database Design Foundations',
    description: 'Learn how structured relational databases store data. Write SQL queries, design schema relations, joins, and database optimizations.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['SQL', 'Database Design', 'PostgreSQL'],
    prerequisite_skills: [],
    difficulty: 'intermediate',
    estimated_hours: 15,
    provider: 'Khan Academy'
  },
  {
    id: 'web-204',
    title: 'TypeScript Deep Dive',
    description: 'Bring type safety to your JavaScript projects. Learn interfaces, generics, advanced union/intersection types, and compiler configurations.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['TypeScript', 'Type Safety'],
    prerequisite_skills: ['JavaScript'],
    difficulty: 'intermediate',
    estimated_hours: 14,
    provider: 'Egghead'
  },
  {
    id: 'web-301',
    title: 'Advanced React & Next.js Production Systems',
    description: 'Learn server-side rendering (SSR), static site generation (SSG), advanced React performance optimizations, and React Server Components.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['Next.js', 'SSR/SSG', 'Web Performance', 'React Server Components'],
    prerequisite_skills: ['React', 'TypeScript'],
    difficulty: 'advanced',
    estimated_hours: 30,
    provider: 'Vercel Academy'
  },
  {
    id: 'web-302',
    title: 'Securing Web Applications',
    description: 'Understand OWASP Top 10 vulnerabilities. Implement user authentication, OAuth2, JWTs, CORS, HTTPS, and prevention of XSS and SQL injection.',
    domain: 'Web Dev',
    type: 'course',
    skills_taught: ['Web Security', 'Authentication', 'OAuth2', 'JWT'],
    prerequisite_skills: ['Node.js', 'Express.js'],
    difficulty: 'advanced',
    estimated_hours: 16,
    provider: 'Pluralsight'
  },
  {
    id: 'web-proj-1',
    title: 'Responsive Portfolio Website',
    description: 'Project: Design, build, and deploy your personal developer portfolio using semantic HTML, CSS Grid, custom transitions, and deploy to Netlify.',
    domain: 'Web Dev',
    type: 'project',
    skills_taught: ['Responsive Design', 'HTML', 'CSS', 'Deployment'],
    prerequisite_skills: ['HTML', 'CSS'],
    difficulty: 'beginner',
    estimated_hours: 10,
    provider: 'Project Sandbox'
  },
  {
    id: 'web-proj-2',
    title: 'Interactive Kanban Board',
    description: 'Project: Build a React drag-and-drop Kanban application. Manage local state, support dark mode, filter tasks, and persist tasks in localStorage.',
    domain: 'Web Dev',
    type: 'project',
    skills_taught: ['React', 'State Management', 'Drag-and-Drop'],
    prerequisite_skills: ['React'],
    difficulty: 'intermediate',
    estimated_hours: 15,
    provider: 'Project Sandbox'
  },
  {
    id: 'web-proj-3',
    title: 'Full-Stack E-Commerce Platform',
    description: 'Project: Build a comprehensive full-stack store with user registration, shopping cart, Stripe integration, admin dashboards, and deployment.',
    domain: 'Web Dev',
    type: 'project',
    skills_taught: ['React', 'TypeScript', 'Node.js', 'Express.js', 'PostgreSQL', 'Stripe Integration'],
    prerequisite_skills: ['React', 'Node.js', 'SQL'],
    difficulty: 'advanced',
    estimated_hours: 45,
    provider: 'Project Sandbox'
  },
  {
    id: 'web-assess-1',
    title: 'Frontend Competency Assessment',
    description: 'Assessment: Solve interactive frontend challenges using JavaScript and React. Tests state management, API data fetching, and component structure.',
    domain: 'Web Dev',
    type: 'assessment',
    skills_taught: ['Frontend Testing', 'Problem Solving'],
    prerequisite_skills: ['React'],
    difficulty: 'intermediate',
    estimated_hours: 3,
    provider: 'PathWise Testing'
  },
  {
    id: 'web-assess-2',
    title: 'Full-Stack Architecture Review',
    description: 'Assessment: Code review and database normalization assessment. Design a system topology that handles high traffic and explain security mitigation.',
    domain: 'Web Dev',
    type: 'assessment',
    skills_taught: ['System Architecture', 'Database Normalization'],
    prerequisite_skills: ['Node.js', 'SQL', 'Web Security'],
    difficulty: 'advanced',
    estimated_hours: 4,
    provider: 'PathWise Testing'
  },

  // ==================== DATA SCIENCE ====================
  {
    id: 'ds-101',
    title: 'Python for Data Analysis',
    description: 'Introduction to Python scripting. Learn syntax, basic data structures (lists, dicts, tuples), loops, and writing clean clean functions.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Python', 'Programming Fundamentals'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 12,
    provider: 'Kaggle Learn'
  },
  {
    id: 'ds-102',
    title: 'Data Science Math & Statistics',
    description: 'Master basic mathematical principles: probability, standard distributions, hypothesis testing, linear regression mathematics, and matrices.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Statistics', 'Probability', 'Linear Algebra'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 20,
    provider: 'Khan Academy'
  },
  {
    id: 'ds-201',
    title: 'Pandas & Numpy Deep Dive',
    description: 'Learn the ultimate libraries for data manipulation. Work with Series, DataFrames, cleaning missing values, grouping, merging, and reshaping data.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Pandas', 'Numpy', 'Data Cleaning'],
    prerequisite_skills: ['Python'],
    difficulty: 'intermediate',
    estimated_hours: 16,
    provider: 'DataCamp'
  },
  {
    id: 'ds-202',
    title: 'Exploratory Data Analysis & Visualization',
    description: 'Tell stories with data. Learn charting libraries like Matplotlib, Seaborn, and Plotly to extract trends, correlations, and outliers.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Data Visualization', 'Matplotlib', 'Seaborn'],
    prerequisite_skills: ['Pandas'],
    difficulty: 'intermediate',
    estimated_hours: 14,
    provider: 'Coursera'
  },
  {
    id: 'ds-203',
    title: 'Practical Machine Learning with Scikit-Learn',
    description: 'Understand ML workflows: train/test splits, cross-validation, classification, regression, clustering, and decision trees.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Machine Learning', 'Scikit-Learn', 'Supervised Learning', 'Clustering'],
    prerequisite_skills: ['Python', 'Statistics', 'Pandas'],
    difficulty: 'intermediate',
    estimated_hours: 25,
    provider: 'Scikit-Learn Academy'
  },
  {
    id: 'ds-301',
    title: 'Feature Engineering & Model Tuning',
    description: 'Supercharge your model accuracy. Learn imputation, scaling, encoding categorical data, hyperparameter tuning (GridSearch/RandomSearch), and pipelines.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Feature Engineering', 'Model Optimization', 'Pipelines'],
    prerequisite_skills: ['Machine Learning'],
    difficulty: 'advanced',
    estimated_hours: 20,
    provider: 'DataCamp'
  },
  {
    id: 'ds-302',
    title: 'Big Data Processing with Spark',
    description: 'Introduction to processing large datasets that do not fit in memory. Learn PySpark, distributed dataframes, and cluster scaling basics.',
    domain: 'Data Science',
    type: 'course',
    skills_taught: ['Spark', 'PySpark', 'Big Data'],
    prerequisite_skills: ['Python', 'Pandas'],
    difficulty: 'advanced',
    estimated_hours: 22,
    provider: 'Databricks Academy'
  },
  {
    id: 'ds-proj-1',
    title: 'Exploratory Movie Dataset Study',
    description: 'Project: Load a dataset of 10,000+ movies, clean null values, analyze genre trends over time, and generate a report with rich visualizations.',
    domain: 'Data Science',
    type: 'project',
    skills_taught: ['Data Cleaning', 'Data Visualization', 'Pandas', 'Matplotlib'],
    prerequisite_skills: ['Pandas'],
    difficulty: 'beginner',
    estimated_hours: 10,
    provider: 'Project Sandbox'
  },
  {
    id: 'ds-proj-2',
    title: 'House Price Prediction Model',
    description: 'Project: Predict real estate pricing. Clean missing features, engineer neighborhood metrics, train regression models, and tune parameters.',
    domain: 'Data Science',
    type: 'project',
    skills_taught: ['Machine Learning', 'Regression', 'Scikit-Learn', 'Feature Engineering'],
    prerequisite_skills: ['Machine Learning'],
    difficulty: 'intermediate',
    estimated_hours: 20,
    provider: 'Kaggle Playground'
  },
  {
    id: 'ds-proj-3',
    title: 'Customer Churn Analysis Dashboard',
    description: 'Project: Analyze telecommunications churn patterns. Build end-to-end models, interpret SHAP values for model transparency, and host a dashboard.',
    domain: 'Data Science',
    type: 'project',
    skills_taught: ['Machine Learning', 'SHAP Analysis', 'Model Deployment', 'Data Visualization'],
    prerequisite_skills: ['Machine Learning', 'Matplotlib'],
    difficulty: 'advanced',
    estimated_hours: 35,
    provider: 'Project Sandbox'
  },
  {
    id: 'ds-assess-1',
    title: 'Statistics & Math Qualification Check',
    description: 'Assessment: Multi-choice and mathematical proof assessment targeting distributions, central limit theorem, and matrix multiplications.',
    domain: 'Data Science',
    type: 'assessment',
    skills_taught: ['Statistical Competency'],
    prerequisite_skills: ['Statistics'],
    difficulty: 'intermediate',
    estimated_hours: 2,
    provider: 'PathWise Testing'
  },
  {
    id: 'ds-assess-2',
    title: 'Machine Learning Workflow Assessment',
    description: 'Assessment: Write a script to ingest an unknown dataset, perform validation, build an ML model, print metrics, and defend your choice of algorithm.',
    domain: 'Data Science',
    type: 'assessment',
    skills_taught: ['ML Architecture', 'Model Validation'],
    prerequisite_skills: ['Machine Learning'],
    difficulty: 'advanced',
    estimated_hours: 5,
    provider: 'PathWise Testing'
  },

  // ==================== ARTIFICIAL INTELLIGENCE & ML ====================
  {
    id: 'ai-101',
    title: 'Python for AI & Math Foundations',
    description: 'Review python scripting along with foundational linear algebra, multivariable calculus (gradients, partial derivatives), and probability.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['Python', 'Linear Algebra', 'Calculus'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 15,
    provider: 'DeepLearning.AI'
  },
  {
    id: 'ai-201',
    title: 'Neural Networks & Deep Learning',
    description: 'Understand backpropagation, forward passes, activation functions (ReLU, Sigmoid), loss functions, and optimizing models via Gradient Descent.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['Neural Networks', 'Deep Learning', 'PyTorch'],
    prerequisite_skills: ['Python', 'Linear Algebra'],
    difficulty: 'intermediate',
    estimated_hours: 25,
    provider: 'DeepLearning.AI'
  },
  {
    id: 'ai-202',
    title: 'Computer Vision Basics (CNNs)',
    description: 'Build convolutional neural networks to classify images, detect boundaries, and analyze image datasets using PyTorch.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['Computer Vision', 'CNN', 'PyTorch', 'Image Classification'],
    prerequisite_skills: ['Neural Networks'],
    difficulty: 'intermediate',
    estimated_hours: 18,
    provider: 'Fast.ai'
  },
  {
    id: 'ai-203',
    title: 'Natural Language Processing (RNNs & Embeddings)',
    description: 'Process text inputs. Learn word tokenization, vocabulary creation, word embeddings (Word2Vec), recurrent neural networks, and LSTMs.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['NLP', 'Word Embeddings', 'RNN', 'LSTMs'],
    prerequisite_skills: ['Neural Networks'],
    difficulty: 'intermediate',
    estimated_hours: 20,
    provider: 'Stanford Online'
  },
  {
    id: 'ai-301',
    title: 'Transformer Architectures & Attention Mechanisms',
    description: 'Learn the breakthrough architecture behind modern LLMs. Code self-attention mechanisms, multi-head attention, and encoder-decoder stacks.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['Transformers', 'Attention Mechanisms', 'Encoder-Decoder'],
    prerequisite_skills: ['Neural Networks', 'NLP'],
    difficulty: 'advanced',
    estimated_hours: 28,
    provider: 'Hugging Face'
  },
  {
    id: 'ai-302',
    title: 'Large Language Models (LLMs) & Prompt Engineering',
    description: 'Dive deep into LLM APIs. Master zero-shot, few-shot prompting, chain-of-thought, retrieval-augmented generation (RAG), and vector databases.',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['LLMs', 'Prompt Engineering', 'RAG', 'Vector Databases'],
    prerequisite_skills: ['NLP'],
    difficulty: 'intermediate',
    estimated_hours: 16,
    provider: 'DeepLearning.AI'
  },
  {
    id: 'ai-303',
    title: 'Fine-tuning & RLHF for Custom LLMs',
    description: 'Take pre-trained LLMs and adapt them to domains. Learn LoRA, QLoRA, parameter-efficient fine-tuning (PEFT), and Reinforcement Learning from Human Feedback (RLHF).',
    domain: 'AI/ML',
    type: 'course',
    skills_taught: ['LLM Fine-tuning', 'LoRA/QLoRA', 'PEFT', 'RLHF'],
    prerequisite_skills: ['Transformers'],
    difficulty: 'advanced',
    estimated_hours: 32,
    provider: 'Hugging Face'
  },
  {
    id: 'ai-proj-1',
    title: 'Handwritten Digit Classifier',
    description: 'Project: The MNIST rite of passage. Implement, train, and test a basic fully connected neural network to recognize handwritten digits using PyTorch.',
    domain: 'AI/ML',
    type: 'project',
    skills_taught: ['PyTorch', 'Neural Networks', 'Image Classification'],
    prerequisite_skills: ['Python'],
    difficulty: 'beginner',
    estimated_hours: 8,
    provider: 'Project Sandbox'
  },
  {
    id: 'ai-proj-2',
    title: 'Semantic Document Search Engine (RAG)',
    description: 'Project: Build a question-answering tool over a directory of PDFs. Chunk documents, calculate embeddings, insert into a vector store, and prompt LLM.',
    domain: 'AI/ML',
    type: 'project',
    skills_taught: ['RAG', 'Vector Databases', 'OpenAI API', 'Text Chunking'],
    prerequisite_skills: ['LLMs'],
    difficulty: 'intermediate',
    estimated_hours: 18,
    provider: 'Project Sandbox'
  },
  {
    id: 'ai-proj-3',
    title: 'Fine-Tuning Llama 3 for Legal Contracts',
    description: 'Project: Prepare a dataset of legal summaries, structure prompts, apply QLoRA, train Llama-3-8B on Google Colab/local GPU, and evaluate outputs.',
    domain: 'AI/ML',
    type: 'project',
    skills_taught: ['LLM Fine-tuning', 'QLoRA', 'Model Evaluation', 'PyTorch'],
    prerequisite_skills: ['LLM Fine-tuning'],
    difficulty: 'advanced',
    estimated_hours: 30,
    provider: 'Project Sandbox'
  },
  {
    id: 'ai-assess-1',
    title: 'Deep Learning Foundation Review',
    description: 'Assessment: Math and coding validation checking your understanding of learning rates, gradients, optimizer formulas, and tensor dimensions.',
    domain: 'AI/ML',
    type: 'assessment',
    skills_taught: ['Mathematical Deep Learning'],
    prerequisite_skills: ['Neural Networks'],
    difficulty: 'intermediate',
    estimated_hours: 3,
    provider: 'PathWise Testing'
  },
  {
    id: 'ai-assess-2',
    title: 'Generative AI Deployment Assessment',
    description: 'Assessment: Build and package an agentic system that calls multiple tools, validates input schema, and handles token failure errors safely.',
    domain: 'AI/ML',
    type: 'assessment',
    skills_taught: ['AI Agent Architecture', 'Safety Guardrails'],
    prerequisite_skills: ['LLMs', 'Transformers'],
    difficulty: 'advanced',
    estimated_hours: 6,
    provider: 'PathWise Testing'
  },

  // ==================== CLOUD & DEVOPS ====================
  {
    id: 'dev-101',
    title: 'Linux Command Line Foundations',
    description: 'Get comfortable with the terminal. Learn directory navigation, file manipulations, processes, file permissions, and standard environment variables.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Linux', 'Terminal Navigation', 'Shell Basics'],
    prerequisite_skills: [],
    difficulty: 'beginner',
    estimated_hours: 10,
    provider: 'Linux Foundation'
  },
  {
    id: 'dev-102',
    title: 'Shell Scripting & Automation',
    description: 'Automate manual operations. Learn bash scripting, cron jobs, file parsing, and piping inputs/outputs to build basic automation tools.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Shell Scripting', 'Bash', 'Automation'],
    prerequisite_skills: ['Linux'],
    difficulty: 'beginner',
    estimated_hours: 12,
    provider: 'Linux Foundation'
  },
  {
    id: 'dev-201',
    title: 'Docker Containers & Packaging',
    description: 'Package applications so they run anywhere. Build Dockerfiles, manage layers, connect networks, store volumes, and utilize Docker Compose.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Docker', 'Containers', 'Microservices'],
    prerequisite_skills: ['Linux'],
    difficulty: 'intermediate',
    estimated_hours: 15,
    provider: 'Docker Institute'
  },
  {
    id: 'dev-202',
    title: 'AWS Infrastructure Core Services',
    description: 'Host infrastructure in the cloud. Cover Virtual Private Clouds (VPC), EC2 servers, S3 object storage, IAM user control, and load balancing.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['AWS', 'Cloud Architecture', 'Networking', 'Security Groups'],
    prerequisite_skills: ['Linux'],
    difficulty: 'intermediate',
    estimated_hours: 22,
    provider: 'Amazon Web Services'
  },
  {
    id: 'dev-203',
    title: 'CI/CD Pipelines with GitHub Actions',
    description: 'Implement automation for builds and tests. Learn custom workflows, triggers, environment secrets, and automated hosting deployments.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['CI/CD', 'GitHub Actions', 'Build Automation'],
    prerequisite_skills: ['Git'],
    difficulty: 'intermediate',
    estimated_hours: 14,
    provider: 'GitHub'
  },
  {
    id: 'dev-301',
    title: 'Kubernetes in Production',
    description: 'Orchestrate microservices at scale. Learn Pods, Deployments, Services, Ingress controllers, configmaps, persistent volumes, and Helm charts.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Kubernetes', 'K8s', 'Orchestration', 'Scaling'],
    prerequisite_skills: ['Docker', 'AWS'],
    difficulty: 'advanced',
    estimated_hours: 28,
    provider: 'Linux Foundation'
  },
  {
    id: 'dev-302',
    title: 'Infrastructure as Code (IaC) with Terraform',
    description: 'Define cloud architecture using declarative configuration. Write providers, modules, state tracking files, and run terraform plans.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Terraform', 'IaC', 'Cloud Provisioning'],
    prerequisite_skills: ['AWS'],
    difficulty: 'advanced',
    estimated_hours: 18,
    provider: 'HashiCorp Learn'
  },
  {
    id: 'dev-303',
    title: 'Monitoring & Observability (Prometheus & Grafana)',
    description: 'Keep systems healthy. Configure Prometheus metric collection, build Grafana performance dashboards, and set up slack alerting systems.',
    domain: 'Cloud/DevOps',
    type: 'course',
    skills_taught: ['Monitoring', 'Prometheus', 'Grafana', 'Alerting'],
    prerequisite_skills: ['Docker'],
    difficulty: 'advanced',
    estimated_hours: 16,
    provider: 'Pluralsight'
  },
  {
    id: 'dev-proj-1',
    title: 'Static Website AWS Deployment',
    description: 'Project: Host a static portfolio on AWS. Use S3 buckets, set up CloudFront CDN cache invalidations, and configure custom Route53 domain names.',
    domain: 'Cloud/DevOps',
    type: 'project',
    skills_taught: ['AWS', 'S3', 'CloudFront', 'DNS Hosting'],
    prerequisite_skills: ['AWS'],
    difficulty: 'beginner',
    estimated_hours: 8,
    provider: 'Project Sandbox'
  },
  {
    id: 'dev-proj-2',
    title: 'Dockerized Flask API with CI/CD',
    description: 'Project: Package a Python API in a Docker container. Create a GitHub Actions workflow to run unit tests, build the image, and push to DockerHub.',
    domain: 'Cloud/DevOps',
    type: 'project',
    skills_taught: ['Docker', 'CI/CD', 'GitHub Actions', 'DockerHub'],
    prerequisite_skills: ['Docker', 'CI/CD'],
    difficulty: 'intermediate',
    estimated_hours: 15,
    provider: 'Project Sandbox'
  },
  {
    id: 'dev-proj-3',
    title: 'Terraformed Multi-Region EKS Cluster',
    description: 'Project: Provision an AWS Elastic Kubernetes Service (EKS) cluster using Terraform module files. Configure auto-scaling nodes and deployments.',
    domain: 'Cloud/DevOps',
    type: 'project',
    skills_taught: ['Terraform', 'Kubernetes', 'EKS', 'AWS Infrastructure'],
    prerequisite_skills: ['Terraform', 'Kubernetes'],
    difficulty: 'advanced',
    estimated_hours: 32,
    provider: 'Project Sandbox'
  },
  {
    id: 'dev-assess-1',
    title: 'Containerization & Networking Review',
    description: 'Assessment: Troubleshoot virtual docker networking bridges, configure multi-stage container optimization builds, and defend layout design.',
    domain: 'Cloud/DevOps',
    type: 'assessment',
    skills_taught: ['Container Security', 'Network Configurations'],
    prerequisite_skills: ['Docker'],
    difficulty: 'intermediate',
    estimated_hours: 3,
    provider: 'PathWise Testing'
  },
  {
    id: 'dev-assess-2',
    title: 'IaC & High-Availability Architecture Defense',
    description: 'Assessment: Write Terraform configuration templates to provision a multi-tier AWS network and build failover procedures.',
    domain: 'Cloud/DevOps',
    type: 'assessment',
    skills_taught: ['Terraform Mastery', 'High Availability Design'],
    prerequisite_skills: ['Terraform', 'Kubernetes'],
    difficulty: 'advanced',
    estimated_hours: 5,
    provider: 'PathWise Testing'
  }
];

// Domains mapping
export const DOMAINS = ['Web Dev', 'Data Science', 'AI/ML', 'Cloud/DevOps'] as const;

// Domain standard skills for gap analysis
export const SKILLS_BY_DOMAIN: Record<string, string[]> = {
  'Web Dev': ['HTML', 'CSS', 'Responsive Design', 'JavaScript', 'DOM Manipulation', 'ES6+', 'Git', 'GitHub', 'Version Control', 'React', 'State Management', 'SPA Architecture', 'Node.js', 'Express.js', 'Backend Development', 'APIs', 'SQL', 'Database Design', 'PostgreSQL', 'TypeScript', 'Type Safety', 'Next.js', 'SSR/SSG', 'Web Performance', 'React Server Components', 'Web Security', 'Authentication', 'OAuth2', 'JWT'],
  'Data Science': ['Python', 'Programming Fundamentals', 'Statistics', 'Probability', 'Linear Algebra', 'Pandas', 'Numpy', 'Data Cleaning', 'Data Visualization', 'Matplotlib', 'Seaborn', 'Machine Learning', 'Scikit-Learn', 'Supervised Learning', 'Clustering', 'Feature Engineering', 'Model Optimization', 'Pipelines', 'Spark', 'PySpark', 'Big Data'],
  'AI/ML': ['Python', 'Linear Algebra', 'Calculus', 'Neural Networks', 'Deep Learning', 'PyTorch', 'Computer Vision', 'CNN', 'Image Classification', 'NLP', 'Word Embeddings', 'RNN', 'LSTMs', 'Transformers', 'Attention Mechanisms', 'Encoder-Decoder', 'LLMs', 'Prompt Engineering', 'RAG', 'Vector Databases', 'LLM Fine-tuning', 'LoRA/QLoRA', 'PEFT', 'RLHF'],
  'Cloud/DevOps': ['Linux', 'Terminal Navigation', 'Shell Basics', 'Shell Scripting', 'Bash', 'Automation', 'Docker', 'Containers', 'Microservices', 'AWS', 'Cloud Architecture', 'Networking', 'Security Groups', 'CI/CD', 'GitHub Actions', 'Build Automation', 'Kubernetes', 'K8s', 'Orchestration', 'Scaling', 'Terraform', 'IaC', 'Cloud Provisioning', 'Monitoring', 'Prometheus', 'Grafana', 'Alerting']
};
